### ISSUE TITLE
Method name does not correspond to its content

### ISSUE THREAD

**Issue by IanaKhitsko** [Vlladdd/Euro-diffusion#2]
https://github.com/Vlladdd/Euro-diffusion/blob/5ce8f3a13ec4949d574e962eeb0a2198c3e44924/lab1/City.swift#L26

IsReady - is about getting the boolean result. If you just update the flag, rename it to smth else (e.g. UpdateReadyState, UpdateStatus etc)

**Comment by Vlladdd** [comment]
fixed
