### ISSUE TITLE
Unreadable method 

### ISSUE THREAD

**Issue by IanaKhitsko** [Vlladdd/Euro-diffusion#6]
https://github.com/Vlladdd/Euro-diffusion/blob/5ce8f3a13ec4949d574e962eeb0a2198c3e44924/lab1/Grid.swift#L73-L89

You need to refactor this method for better readability. I've just made the first try, but it seems that you can make it better on swift

    private func checkCountries() -> Bool{
        for country in countries {
            var possible = false
            for city in country.cities{
                for neighbour in city.neighbors {
                    possible |= city.motifs != neighbour.motifs 
                    }
                }
            }
            if !possible {
                return false
            }
        }
        return true
    }

**Comment by Vlladdd** [comment]
fixed
